using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SJAHE_BASE_LIBRARY.Models
{
    [Table("PY_EmployeeAbsenteeismComponents")]
    public class PY_EmployeeAbsenteeismComponents
    {
        [Key]
        public int EmployeeAbsenteeismComponents { get; set; }
        public string EmployeeNo { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public bool FlagInSal { get; set; }
        public bool FlagOutSal { get; set; }
        public bool FlagInOvt { get; set; }
        public bool FlagOutOvt { get; set; }
        public bool FlagInAbs { get; set; }
        public bool FlagOutAbs { get; set; }
        public decimal MaxDateSal { get; set; }
        public decimal MaxDateOvt { get; set; }
        public decimal MaxDateAbs { get; set; }
        public decimal DayJoinSal { get; set; }
        public decimal DayJoinOvt { get; set; }
        public decimal DayJoinAbs { get; set; }
        public decimal DayResSal { get; set; }
        public decimal DayResOvt { get; set; }
        public decimal DayResAbs { get; set; }
        public decimal NormDaySal { get; set; }
        public decimal NormHolSal { get; set; }
        public decimal NormShoSal { get; set; }
        public decimal NormHolShoSal { get; set; }
        public decimal NormDayOvt { get; set; }
        public decimal NormHolOvt { get; set; }
        public decimal NormShoOvt { get; set; }
        public decimal NormHolShoOvt { get; set; }
        public decimal NormDayAbs { get; set; }
        public decimal NormHolAbs { get; set; }
        public decimal NormShoAbs { get; set; }
        public decimal NormHolShoAbs { get; set; }
        public decimal NormHouDaySal { get; set; }
        public decimal NormHouHolSal { get; set; }
        public decimal NormHouShoSal { get; set; }
        public decimal NormHouHolShoSal { get; set; }
        public decimal NormHouDayOvt { get; set; }
        public decimal NormHouHolOvt { get; set; }
        public decimal NormHouShoOvt { get; set; }
        public decimal NormHouHolShoOvt { get; set; }
        public decimal NormHouDayAbs { get; set; }
        public decimal NormHouHolAbs { get; set; }
        public decimal NormHouShoAbs { get; set; }
        public decimal NormHouHolShoAbs { get; set; }
        public decimal NormBreHouDaySal { get; set; }
        public decimal NormBreHouShoSal { get; set; }
        public decimal NormBreHouDayOvt { get; set; }
        public decimal NormBreHouShoOvt { get; set; }
        public decimal NormBreHouDayAbs { get; set; }
        public decimal NormBreHouShoAbs { get; set; }
        public decimal WorkCalDaySal { get; set; }
        public decimal WorkCalHolSal { get; set; }
        public decimal WorkCalShoSal { get; set; }
        public decimal WorkCalHolShoSal { get; set; }
        public decimal WorkCalDayOvt { get; set; }
        public decimal WorkCalHolOvt { get; set; }
        public decimal WorkCalShoOvt { get; set; }
        public decimal WorkCalHolShoOvt { get; set; }
        public decimal WorkCalDayAbs { get; set; }
        public decimal WorkCalHolAbs { get; set; }
        public decimal WorkCalShoAbs { get; set; }
        public decimal WorkCalHolShoAbs { get; set; }
        public decimal WorkCalHouDaySal { get; set; }
        public decimal WorkCalHouHolSal { get; set; }
        public decimal WorkCalHouShoSal { get; set; }
        public decimal WorkCalHouHolShoSal { get; set; }
        public decimal WorkCalHouDayOvt { get; set; }
        public decimal WorkCalHouHolOvt { get; set; }
        public decimal WorkCalHouShoOvt { get; set; }
        public decimal WorkCalHouHolShoOvt { get; set; }
        public decimal WorkCalHouDayAbs { get; set; }
        public decimal WorkCalHouHolAbs { get; set; }
        public decimal WorkCalHouShoAbs { get; set; }
        public decimal WorkCalHouHolShoAbs { get; set; }
        public decimal WorkCalBreHouDaySal { get; set; }
        public decimal WorkCalBreHouShoSal { get; set; }
        public decimal WorkCalBreHouDayOvt { get; set; }
        public decimal WorkCalBreHouShoOvt { get; set; }
        public decimal WorkCalBreHouDayAbs { get; set; }
        public decimal WorkCalBreHouShoAbs { get; set; }
        public decimal WorkDaySal { get; set; }
        public decimal WorkHolSal { get; set; }
        public decimal WorkShoSal { get; set; }
        public decimal WorkHolShoSal { get; set; }
        public decimal WorkDayOvt { get; set; }
        public decimal WorkHolOvt { get; set; }
        public decimal WorkShoOvt { get; set; }
        public decimal WorkHolShoOvt { get; set; }
        public decimal WorkDayAbs { get; set; }
        public decimal WorkHolAbs { get; set; }
        public decimal WorkShoAbs { get; set; }
        public decimal WorkHolShoAbs { get; set; }
        public decimal WorkHouDaySal { get; set; }
        public decimal WorkHouHolSal { get; set; }
        public decimal WorkHouShoSal { get; set; }
        public decimal WorkHouHolShoSal { get; set; }
        public decimal WorkHouDayOvt { get; set; }
        public decimal WorkHouHolOvt { get; set; }
        public decimal WorkHouShoOvt { get; set; }
        public decimal WorkHouHolShoOvt { get; set; }
        public decimal WorkHouDayAbs { get; set; }
        public decimal WorkHouHolAbs { get; set; }
        public decimal WorkHouShoAbs { get; set; }
        public decimal WorkHouHolShoAbs { get; set; }
        public decimal WorkBreHouDaySal { get; set; }
        public decimal WorkBreHouShoSal { get; set; }
        public decimal WorkBreHouDayOvt { get; set; }
        public decimal WorkBreHouShoOvt { get; set; }
        public decimal WorkBreHouDayAbs { get; set; }
        public decimal WorkBreHouShoAbs { get; set; }
        public decimal CalDaySal { get; set; }
        public decimal CalHolSal { get; set; }
        public decimal CalShoSal { get; set; }
        public decimal CalHolShoSal { get; set; }
        public decimal CalDayOvt { get; set; }
        public decimal CalHolOvt { get; set; }
        public decimal CalShoOvt { get; set; }
        public decimal CalHolShoOvt { get; set; }
        public decimal CalDayAbs { get; set; }
        public decimal CalHolAbs { get; set; }
        public decimal CalShoAbs { get; set; }
        public decimal CalHolShoAbs { get; set; }
        public decimal CalHouDaySal { get; set; }
        public decimal CalHouHolSal { get; set; }
        public decimal CalHouShoSal { get; set; }
        public decimal CalHouHolShoSal { get; set; }
        public decimal CalHouDayOvt { get; set; }
        public decimal CalHouHolOvt { get; set; }
        public decimal CalHouShoOvt { get; set; }
        public decimal CalHouHolShoOvt { get; set; }
        public decimal CalHouDayAbs { get; set; }
        public decimal CalHouHolAbs { get; set; }
        public decimal CalHouShoAbs { get; set; }
        public decimal CalHouHolShoAbs { get; set; }
        public decimal CalBreHouDaySal { get; set; }
        public decimal CalBreHouShoSal { get; set; }
        public decimal CalBreHouDayOvt { get; set; }
        public decimal CalBreHouShoOvt { get; set; }
        public decimal CalBreHouDayAbs { get; set; }
        public decimal CalBreHouShoAbs { get; set; }
        public decimal ShifDaySal { get; set; }
        public decimal MealDaySal { get; set; }
        public decimal TranDaySal { get; set; }
        public decimal Oth1DaySal { get; set; }
        public decimal Oth2DaySal { get; set; }
        public decimal Oth3DaySal { get; set; }
        public decimal ShifDayOvt { get; set; }
        public decimal MealDayOvt { get; set; }
        public decimal TranDayOvt { get; set; }
        public decimal Oth1DayOvt { get; set; }
        public decimal Oth2DayOvt { get; set; }
        public decimal Oth3DayOvt { get; set; }
        public decimal ShifDayAbs { get; set; }
        public decimal MealDayAbs { get; set; }
        public decimal TranDayAbs { get; set; }
        public decimal Oth1DayAbs { get; set; }
        public decimal Oth2DayAbs { get; set; }
        public decimal Oth3DayAbs { get; set; }
        public decimal ConvNor1 { get; set; }
        public decimal ConvNor2 { get; set; }
        public decimal ConvNor3 { get; set; }
        public decimal ConvHol1 { get; set; }
        public decimal ConvHol2 { get; set; }
        public decimal ConvHol3 { get; set; }
        public decimal ConvSho1 { get; set; }
        public decimal ConvSho2 { get; set; }
        public decimal ConvSho3 { get; set; }
        public decimal OTConv { get; set; }
        public decimal OTConvPrev { get; set; }
        public decimal OTActual { get; set; }
        public decimal OTActualPrev { get; set; }
        public decimal OvtDay { get; set; }
        public decimal OvtHol { get; set; }
        public decimal OvtHolSho { get; set; }
        public decimal OvtBot { get; set; }
        public decimal OvtHouDay { get; set; }
        public decimal OvtHouHol { get; set; }
        public decimal OvtHouHolSho { get; set; }
        public decimal OvtBreDay { get; set; }
        public decimal OvtBreHol { get; set; }
        public decimal OvtBreHolSho { get; set; }
        public decimal AbsHou1 { get; set; }
        public decimal AbsHou2 { get; set; }
        public decimal AbsHou3 { get; set; }
        public decimal AbsHou4 { get; set; }
        public decimal AbsHou5 { get; set; }
        public decimal AbsHou6 { get; set; }
        public decimal AbsHou7 { get; set; }
        public decimal AbsHou8 { get; set; }
        public decimal AbsHou9 { get; set; }
        public decimal AbsHou10 { get; set; }
        public decimal AbsDay1 { get; set; }
        public decimal AbsDay2 { get; set; }
        public decimal AbsDay3 { get; set; }
        public decimal AbsDay4 { get; set; }
        public decimal AbsDay5 { get; set; }
        public decimal AbsDay6 { get; set; }
        public decimal AbsDay7 { get; set; }
        public decimal AbsDay8 { get; set; }
        public decimal AbsDay9 { get; set; }
        public decimal AbsDay10 { get; set; }
        public decimal OvtTarPrev { get; set; }
        public decimal OvtTarCur { get; set; }
        public decimal OvtAmt { get; set; }
        public decimal ShiftAmt { get; set; }
        public decimal MealAmt { get; set; }
        public decimal TranAmt { get; set; }
        public decimal Oth1Amt { get; set; }
        public decimal Oth2Amt { get; set; }
        public decimal Oth3Amt { get; set; }
        public decimal AbsNor01 { get; set; }
        public decimal AbsNor02 { get; set; }
        public decimal AbsNor03 { get; set; }
        public decimal AbsNor04 { get; set; }
        public decimal AbsNor05 { get; set; }
        public decimal AbsNor06 { get; set; }
        public decimal AbsNor07 { get; set; }
        public decimal AbsNor08 { get; set; }
        public decimal AbsNor09 { get; set; }
        public decimal AbsNor10 { get; set; }
        public decimal AbsNor11 { get; set; }
        public decimal AbsNor12 { get; set; }
        public decimal AbsNor13 { get; set; }
        public decimal AbsNor14 { get; set; }
        public decimal AbsNor15 { get; set; }
        public decimal AbsNor16 { get; set; }
        public decimal AbsNor17 { get; set; }
        public decimal AbsNor18 { get; set; }
        public decimal AbsNor19 { get; set; }
        public decimal AbsNor20 { get; set; }
        public decimal AbsNor21 { get; set; }
        public decimal AbsNor22 { get; set; }
        public decimal AbsNor23 { get; set; }
        public decimal AbsNor24 { get; set; }
        public decimal AbsNor25 { get; set; }
        public decimal OTHol01 { get; set; }
        public decimal OTHol02 { get; set; }
        public decimal OTHol03 { get; set; }
        public decimal OTHol04 { get; set; }
        public decimal OTHol05 { get; set; }
        public decimal OTHol06 { get; set; }
        public decimal OTHol07 { get; set; }
        public decimal OTHol08 { get; set; }
        public decimal OTHol09 { get; set; }
        public decimal OTHol10 { get; set; }
        public decimal OTHol11 { get; set; }
        public decimal OTHol12 { get; set; }
        public decimal OTHol13 { get; set; }
        public decimal OTHol14 { get; set; }
        public decimal OTHol15 { get; set; }
        public decimal OTHol16 { get; set; }
        public decimal OTHol17 { get; set; }
        public decimal OTHol18 { get; set; }
        public decimal OTHol19 { get; set; }
        public decimal OTHol20 { get; set; }
        public decimal OTHol21 { get; set; }
        public decimal OTHol22 { get; set; }
        public decimal OTHol23 { get; set; }
        public decimal OTHol24 { get; set; }
        public decimal OTHol25 { get; set; }
        public decimal OTNor01 { get; set; }
        public decimal OTNor02 { get; set; }
        public decimal OTNor03 { get; set; }
        public decimal OTNor04 { get; set; }
        public decimal OTNor05 { get; set; }
        public decimal OTNor06 { get; set; }
        public decimal OTNor07 { get; set; }
        public decimal OTNor08 { get; set; }
        public decimal OTNor09 { get; set; }
        public decimal OTNor10 { get; set; }
        public decimal OTNor11 { get; set; }
        public decimal OTNor12 { get; set; }
        public decimal OTNor13 { get; set; }
        public decimal OTNor14 { get; set; }
        public decimal OTNor15 { get; set; }
        public decimal OTNor16 { get; set; }
        public decimal OTNor17 { get; set; }
        public decimal OTNor18 { get; set; }
        public decimal OTNor19 { get; set; }
        public decimal OTNor20 { get; set; }
        public decimal OTNor21 { get; set; }
        public decimal OTNor22 { get; set; }
        public decimal OTNor23 { get; set; }
        public decimal OTNor24 { get; set; }
        public decimal OTNor25 { get; set; }
        public decimal OTSho01 { get; set; }
        public decimal OTSho02 { get; set; }
        public decimal OTSho03 { get; set; }
        public decimal OTSho04 { get; set; }
        public decimal OTSho05 { get; set; }
        public decimal OTSho06 { get; set; }
        public decimal OTSho07 { get; set; }
        public decimal OTSho08 { get; set; }
        public decimal OTSho09 { get; set; }
        public decimal OTSho10 { get; set; }
        public decimal OTSho11 { get; set; }
        public decimal OTSho12 { get; set; }
        public decimal OTSho13 { get; set; }
        public decimal OTSho14 { get; set; }
        public decimal OTSho15 { get; set; }
        public decimal OTSho16 { get; set; }
        public decimal OTSho17 { get; set; }
        public decimal OTSho18 { get; set; }
        public decimal OTSho19 { get; set; }
        public decimal OTSho20 { get; set; }
        public decimal OTSho21 { get; set; }
        public decimal OTSho22 { get; set; }
        public decimal OTSho23 { get; set; }
        public decimal OTSho24 { get; set; }
        public decimal OTSho25 { get; set; }
        public decimal OTHolSho01 { get; set; }
        public decimal OTHolSho02 { get; set; }
        public decimal OTHolSho03 { get; set; }
        public decimal OTHolSho04 { get; set; }
        public decimal OTHolSho05 { get; set; }
        public decimal OTHolSho06 { get; set; }
        public decimal OTHolSho07 { get; set; }
        public decimal OTHolSho08 { get; set; }
        public decimal OTHolSho09 { get; set; }
        public decimal OTHolSho10 { get; set; }
        public decimal OTHolSho11 { get; set; }
        public decimal OTHolSho12 { get; set; }
        public decimal OTHolSho13 { get; set; }
        public decimal OTHolSho14 { get; set; }
        public decimal OTHolSho15 { get; set; }
        public decimal OTHolSho16 { get; set; }
        public decimal OTHolSho17 { get; set; }
        public decimal OTHolSho18 { get; set; }
        public decimal OTHolSho19 { get; set; }
        public decimal OTHolSho20 { get; set; }
        public decimal OTHolSho21 { get; set; }
        public decimal OTHolSho22 { get; set; }
        public decimal OTHolSho23 { get; set; }
        public decimal OTHolSho24 { get; set; }
        public decimal OTHolSho25 { get; set; }
        public decimal AnnLeaveSal { get; set; }
        public decimal LSLeaveSal { get; set; }
        public decimal SpLeaveSal { get; set; }
        public decimal UpLeaveSal { get; set; }
        public decimal CompLeaveSal { get; set; }
        public decimal AnnLeaveOvt { get; set; }
        public decimal LSLeaveOvt { get; set; }
        public decimal SpLeaveOvt { get; set; }
        public decimal UpLeaveOvt { get; set; }
        public decimal CompLeaveOvt { get; set; }
        public decimal AnnLeaveAbs { get; set; }
        public decimal LSLeaveAbs { get; set; }
        public decimal SpLeaveAbs { get; set; }
        public decimal UpLeaveAbs { get; set; }
        public decimal CompLeaveAbs { get; set; }
        public string Note { get; set; }
        public int CreatedBy { get; set; }
        public DateTime DateCreated { get; set; }
        public decimal AnnHolDay { get; set; }

        public virtual PA_EmployeeOccupation PA_EmployeeOccupation { get; set; }
    }
}